project_id = "zcsoudhbfeiszutasead"

[functions.analyze-floor-plan]
verify_jwt = false

[functions.parse-budget-pdf]
verify_jwt = false

[functions.parse-inputs-import]
verify_jwt = false

[functions.parse-budget-items]
verify_jwt = false

[functions.parse-macros-import]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.transition-supply-status]
verify_jwt = false
